# Generated by Django 4.2.13 on 2024-05-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_customvideotrack_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customvideomodel",
            name="error_message",
            field=models.TextField(blank=True),
        ),
    ]
