# Generated by Django 4.2.13 on 2024-05-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailvideos", "0014_alter_videotrack_file_alter_videotrack_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="error_message",
            field=models.TextField(blank=True),
        ),
    ]
